# Generated by Django 2.0 on 2018-02-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_has_passed', models.BooleanField(default=False)),
                ('record_no', models.CharField(max_length=200)),
                ('record_date', models.DateTimeField(verbose_name='Date Record')),
                ('record_isVIP', models.BooleanField(default=False)),
            ],
        ),
    ]
