# Generated by Django 2.0 on 2018-03-19 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('service_window', models.IntegerField(default=0)),
                ('no', models.CharField(max_length=22)),
                ('wait_no', models.CharField(max_length=10)),
                ('terminal_no', models.CharField(max_length=10)),
                ('bank_no', models.CharField(blank=True, max_length=10, null=True)),
                ('institution_no', models.CharField(max_length=10)),
                ('arrive_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='GetNo DateTime')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Service DateTime')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Service DateTime')),
                ('isVIP', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('bank_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distribute.Bank')),
                ('institute_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distribute.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='vipCust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=22)),
                ('openbankno', models.CharField(max_length=10, verbose_name='Open bank NO')),
            ],
        ),
        migrations.CreateModel(
            name='VRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('service_window', models.IntegerField(default=0)),
                ('no', models.CharField(max_length=22)),
                ('wait_no', models.CharField(max_length=10)),
                ('terminal_no', models.CharField(max_length=10)),
                ('bank_no', models.CharField(max_length=10)),
                ('institution_no', models.CharField(blank=True, max_length=10, null=True)),
                ('arrive_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='GetNo DateTime')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Service DateTime')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Service DateTime')),
                ('isVIP', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='institute_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distribute.Institute'),
        ),
    ]
