# Generated by Django 2.0 on 2018-02-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribute', '0002_auto_20180227_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='NRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_status', models.IntegerField(default=0)),
                ('record_no', models.CharField(max_length=22)),
                ('record_arrive_date', models.DateTimeField(verbose_name='Date Record')),
                ('record_start_date', models.DateTimeField(verbose_name='Date Record')),
                ('record_end_date', models.DateTimeField(verbose_name='Date Record')),
                ('record_wait_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_status', models.IntegerField(default=0)),
                ('record_no', models.CharField(max_length=22)),
                ('record_arrive_date', models.DateTimeField(verbose_name='Date Record')),
                ('record_start_date', models.DateTimeField(verbose_name='Date Record')),
                ('record_end_date', models.DateTimeField(verbose_name='Date Record')),
                ('record_wait_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='DRecord',
        ),
    ]
