# Generated by Django 2.0 on 2018-02-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Distribute', '0003_auto_20180227_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nrecord',
            old_name='record_arrive_date',
            new_name='arrive_date',
        ),
        migrations.RenameField(
            model_name='nrecord',
            old_name='record_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='nrecord',
            old_name='record_no',
            new_name='no',
        ),
        migrations.RenameField(
            model_name='nrecord',
            old_name='record_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='nrecord',
            old_name='record_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='nrecord',
            old_name='record_wait_no',
            new_name='wait_no',
        ),
        migrations.RenameField(
            model_name='vrecord',
            old_name='record_arrive_date',
            new_name='arrive_date',
        ),
        migrations.RenameField(
            model_name='vrecord',
            old_name='record_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='vrecord',
            old_name='record_no',
            new_name='no',
        ),
        migrations.RenameField(
            model_name='vrecord',
            old_name='record_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='vrecord',
            old_name='record_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='vrecord',
            old_name='record_wait_no',
            new_name='wait_no',
        ),
    ]
